/// <reference types="vite/client" />
// This file is automatically generated.
// It contains type declarations for Vite's client-side code
// It includes types for environment variables and other Vite-specific features